[project]
name = "clite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "black>=24.10.0",
    "pyright>=1.1.391",
    "pytest>=8.3.4",
    "ruff>=0.9.0",
]
